version: "3.8"

services:
  # backend:
  #   image: pdfgenerator-dev-api
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: pdfgenerator-backend
  #   volumes:
  #     - ./api/src:/api/src
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - NODE_ENV=development
  # frontend:
  #   image: pdfgenerator-dev-front
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   container_name: pdfgenerator-frontend
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./front/src:/front/src
  #     - ./front/public:/front/public
  #   ports:
  #     - 3000:3000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pdfgenerator
      POSTGRES_USER: pdfgenerator
    volumes:
      - ./dataset/database_data:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
